//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientsHistory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public int Age { get; set; }
        public bool Gender { get; set; }
        public string DoctorName { get; set; }
        public string RoomNo { get; set; }
        public string ReceptionistName { get; set; }
        public System.DateTime Date { get; set; }
    }
}
